on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    name: "black"
    steps:
      - uses: davidslusser/actions_python_black@v1.0.0
        with:
          src: "django_project"
          options: ""
          pip_install_command: "pip install .[dev]"
